# 7.- Arreglos con NUMPY

En este capítulo aprenderás a utilizar algunas cualidades básicas de NumPy (Numerical Python).
NumPy es una de las librerías más populares de Python, ya que puede procesar listas de múltiples
dimensiones

## 7.2.- Arreglo de Datos

Como en la sección anterior, invocaremos a la librería NumPy como np

In [ ]:
import numpy as np

Armemos un arreglo de todos los factoriales del 1 al 6

In [ ]:
factoriales = np.array([np.math.factorial(n) for n in range(1, 7)])
factoriales
array([  1,   2,   6,  24, 120, 720])

Verifica el tipo de objeto que generamos

In [ ]:
type(factoriales)
<class 'numpy.ndarray'>

La función array copia automáticamente las dimensiones del argumento. Por ejemplo, el siguiente arreglo (array) está formado por tres filas y dos columnas.

In [ ]:
matriz = np.array([[1, 2], [3, 4], [5, 6]])
matriz
array([[1, 2],
       [3, 4],
       [5, 6]])

#### Por tu cuenta

Arma un arreglo de una dimensión desde una compresnidón de lista que produce todos los números nones del 1 al 30

In [ ]:
nones = np.array([n for n in range(1, 31, 2)])
nones
array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

### 7.2.2 - Atributos de Arreglos

En esta sección usaremos los siguientes 2 arreglos

enteros = np.array([[9,10,11,12],[8,7,6,5]])

flotantes=np.array([[9**(1/2),10**(1/2),3.33,],[10/3,3.4,3.03]])

In [ ]:
enteros = np.array([[9, 10, 11, 12], [8, 7, 6, 5]])

flotantes = np.array([[9**(1/2), 10**(1/2), 3.33], [10/3, 3.4, 3.03]])

enteros, flotantes

In [ ]:
(array([[ 9, 10, 11, 12],
        [ 8,  7,  6,  5]]), 
 array([[3.        , 3.16227766, 3.33      ],
        [3.33333333, 3.4       , 3.03      ]]))

Checa el tipo de elemento con dtype

In [ ]:
enteros.dtype, flotantes.dtype

In [ ]:
(dtype('int64'), dtype('float64'))

Revisa que puedes ver dimensione con ndim y forma con shape del arreglo

In [ ]:
enteros.ndim, enteros.shape, flotantes.ndim, flotantes.shape

In [ ]:
(2, (2, 4), 2, (2, 3))

Size y itemsize te permite conocer el numero de elemntos y de bytes para almacenar

In [ ]:
enteros.size, enteros.itemsize, flotantes.size, flotantes.itemsize
(8, 8, 6, 8)

Se puede iterar facilmente a través de un arreglo

In [ ]:
for fila in enteros:
    for elemento in fila:
        print(elemento, end=" ")
9 10 11 12 8 7 6 5

#### Por tu cuenta

Para el arreglo que armaste en el "Por tu cuenta" previo, checa el numero de dmiensiones y forma del arreglo

In [ ]:
nones.ndim, nones.shape

In [ ]:
(1, (15,))

### 7.2.3 - Creando Arreglos desde Rangos

La función arange (una sola R!!!!) nos permite crear rangos de enteros. Crea:

- Un arreglo del 0 al 7
- Un arreglo del 3 al 7
- Un arreglo del 12 al 2 en pasos de 3 en 3 (si, en orden inverso)

In [ ]:
arr1 = np.arange(0, 8)
arr2 = np.arange(3, 8)
arr3 = np.arange(12, 1, -3)

arr1, arr2, arr3

In [ ]:
(array([0, 1, 2, 3, 4, 5, 6, 7]), 
 array([3, 4, 5, 6, 7]), 
 array([12,  9,  6,  3]))

Tambien se pueden usar tamaños de paso no enteros. Crea un arreglo con linspace de 0 al 1 que vaya de .25 en .25

In [ ]:
arr_linspace = np.linspace(0, 1, num=5)
arr_linspace
array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Y se puede cambiar la forma del arreglo con reshape. Crea un arreglo con arange que vaya del 21 al 1 en orden inverso, y luego dale forma de matriz de 4x5

In [ ]:
arr = np.arange(21, 1, -1).reshape(4, 5)
arr
array([[21, 20, 19, 18, 17],
       [16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2]])

Checate que si el arreglo tiene 1000 o más elementos, numpy no muestra la totalidad de los datos. Generaun arreglo de 0 a 9999 y dale forma de 5 x 2000

In [ ]:
arr_grande = np.arange(10000).reshape(5, 2000)
arr_grande
array([[   0,    1,    2, ..., 1997, 1998, 1999],
       [2000, 2001, 2002, ..., 3997, 3998, 3999],
       [4000, 4001, 4002, ..., 5997, 5998, 5999],
       [6000, 6001, 6002, ..., 7997, 7998, 7999],
       [8000, 8001, 8002, ..., 9997, 9998, 9999]])


#### Por tu cuenta

Usa la función arange para crear una rreglo de 20 enteros pares del 42 al 80, y luego rearmalo en una matriz de 4x5

In [ ]:
arr_pares = np.arange(42, 82, 2).reshape(4, 5)
arr_pares
array([[42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60],
       [62, 64, 66, 68, 70],
       [72, 74, 76, 78, 80]])


### 7.2.4 - ¿Que tan más rapido es un arreglo?

Usa la magia %timeit y la librería random para crear una comprensión de lista que simule un tiro de dao 6000000 de veces y medir su tiempo

In [ ]:
import random

%timeit [random.randint(1, 6) for _ in range(6000000)]

Ahora usa %timeit para medir el tiempo de un tiro de dado 6000000 de veces pero hecho con arreglo

In [ ]:
%timeit np.random.randint(1, 7, 6000000)

#### Por tu cuenta

Usa %timeit para ver que es mas rapido - una lista que sume todos los enteros del 0 al 9 999 999 o un arreglo que haga lo mismo con el metodo sum

In [ ]:
%timeit sum(range(10000000))
%timeit np.sum(np.arange(10000000))

## 7.3.- Operaciones con Arreglos

Arma un arreglo de todos los pares del 2 al 15.

- Sumale 1 al arreglo
- Multiplicalo por 3
- Sacale raiz cuadrada

In [ ]:
arr_pares = np.arange(2, 16, 2)

arr_suma = arr_pares + 1
arr_multi = arr_pares * 3
arr_raiz = np.sqrt(arr_pares)

arr_suma, arr_multi, arr_raiz

In [ ]:
(array([ 3,  5,  7,  9, 11, 13, 15]), 
 array([ 6, 12, 18, 24, 30, 36, 42]), 
 array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766,
       3.46410162, 3.74165739]))

Al mismo arreglo, aplicale un +=10

In [ ]:
import numpy as np

arr_pares = np.arange(2, 16, 2)

arr_suma = arr_pares + 1
arr_multi = arr_pares * 3
arr_raiz = np.sqrt(arr_pares)

arr_suma += 10
arr_multi += 10
arr_raiz += 10

arr_suma, arr_multi, arr_raiz

In [ ]:
(array([13, 15, 17, 19, 21, 23, 25]),
 array([16, 22, 28, 34, 40, 46, 52]),
 array([11.41421356, 12.        , 12.44948974, 12.82842712, 13.16227766,
        13.46410162, 13.74165739]))

Arma un arreglo (lista1) que vaya del 2 al 18 de 3 en 3, y otro arreglo (lista2) usando linspace que vaya del -2 al 20 dividido en 6 numeros

- Resta lista1 de lista2
- divide lista2 entre lista1

In [ ]:
import numpy as np

lista1 = np.arange(2, 19, 3)
lista2 = np.linspace(-2, 20, 6)

resta = lista2 - lista1
division = lista2 / lista1

resta, division

In [ ]:
(array([ -4. ,  -3.6,  -3.2,  -2.8,  -2.4, -13. ]),
 array([-1.        , -0.26666667, -0.03125   ,  0.15789474,  0.29166667,
         0.38888889]))

También puedes comparar los arreglos

In [ ]:
comparacion_mayor = lista1 > lista2
comparacion_menor = lista1 < lista2
comparacion_igual = lista1 == lista2

comparacion_mayor, comparacion_menor, comparacion_igual
(array([ True,  True,  True,  True,  True,  True]),
 array([False, False, False, False, False, False]),
 array([False, False, False, False, False, False]))


#### Por tu cuenta

Crea un arreglo de los valores que vayan del 1 al 5, y luego elvealo al cuadrado usando **

In [ ]:
import numpy as np

arr = np.arange(1, 6)
arr_cuadrado = arr ** 2

arr_cuadrado

In [ ]:
array([ 1,  4,  9, 16, 25])

### 7.3.2.- Métodos de Cálculo

Considera el siguiente arreglo 

ventas=np.array( [[554,606,710,851],[1244,898,416,1763],
 [841,655,1105,1067]])


In [ ]:
import numpy as np

ventas = np.array([[554, 606, 710, 851], 
                   [1244, 898, 416, 1763], 
                   [841, 655, 1105, 1067]])

suma_total = np.sum(ventas)
suma_columnas = np.sum(ventas, axis=0)
suma_filas = np.sum(ventas, axis=1)

promedio_total = np.mean(ventas)
promedio_columnas = np.mean(ventas, axis=0)
promedio_filas = np.mean(ventas, axis=1)

suma_total, suma_columnas, suma_filas, promedio_total, promedio_co
(10130, 
 array([2639, 2159, 2231, 3681]), 
 array([2721, 4321, 3668]), 
 844.1666666666666, 
 array([879.66666667, 719.66666667, 743.66666667, 1227.        ]), 
 array([ 680.25, 1320.25, 916.75]))


Podemos usar métodos para calcular la sum, min, max, mean, std, var. 

In [ ]:
suma = np.sum(ventas)
minimo = np.min(ventas)
maximo = np.max(ventas)
media = np.mean(ventas)
desv_estandar = np.std(ventas)
varianza = np.var(ventas)

suma, minimo, maximo, media, desv_estandar, varianza

In [ ]:
(10130, 416, 1763, 844.1666666666666, 368.5582443185182, 135832.80555555556)

También es posible hacerlo por filas y columnas. Checa como se hace con axis = 1 y 0

In [ ]:
suma_filas = np.sum(ventas, axis=1)
suma_columnas = np.sum(ventas, axis=0)

min_filas = np.min(ventas, axis=1)
min_columnas = np.min(ventas, axis=0)

max_filas = np.max(ventas, axis=1)
max_columnas = np.max(ventas, axis=0)

media_filas = np.mean(ventas, axis=1)
media_columnas = np.mean(ventas, axis=0)

std_filas = np.std(ventas, axis=1)
std_columnas = np.std(ventas, axis=0)

var_filas = np.var(ventas, axis=1)
var_columnas = np.var(ventas, axis=0)

(suma_filas, suma_columnas, min_filas, min_columnas, max_filas, max_columnas, 
 media_filas, media_columnas, std_filas, std_columnas, var_filas, var_columnas)

In [ ]:
(array([2721, 4321, 3668]), 
 array([2639, 2159, 2231, 3681]), 
 array([554, 416, 655]), 
 array([554, 606, 416, 851]), 
 array([851, 1763, 1105]), 
 array([1244, 898, 1105, 1763]), 
 array([ 680.25, 1080.25, 917. ]), 
 array([879.66666667, 719.66666667, 743.66666667, 1227. ]), 
 array([121.71512226, 526.35131384, 183.69577671]), 
 array([285.47737016, 128.00913026, 298.22119706, 395.34301187]), 
 array([14814.1875, 277051.1875, 33742. ]), 
 array([81500.22222222, 16392.22222222, 88938.22222222, 156299.33333333]))


#### Por tu cuenta

Usa el generador de numeros aleatoreos de numpy (np.random.randint) para crear una rreglo de 12 calificaciones aleatorias del 60 al 100, y luego dale forma en una matriz de 3x4. Calcula el promedio de todas las calificaciones, el promedio de cada columna y de cada fila. 

In [ ]:
import numpy as np

calificaciones = np.random.randint(60, 101, 12).reshape(3, 4)

promedio_total = np.mean(calificaciones)
promedio_columnas = np.mean(calificaciones, axis=0)
promedio_filas = np.mean(calificaciones, axis=1)

calificaciones, promedio_total, promedio_columnas, promedio_filas

In [ ]:
(array([[ 78,  89,  95,  74],
        [ 82,  90,  97,  87],
        [ 73,  99,  80,  93]]), 
 86.08333333333333, 
 array([77.66666667, 92.66666667, 90.66666667, 84.66666667]), 
 array([84., 89., 86.]))

## 7.4.- Indexando y Cortando arreglos

Crea el arreglo

ventas=np.array ([[ 554, 606, 710, 851],
 [1244, 898, 416, 1763],
 [ 841, 655, 1105, 1067]])
 
 - Selecciona el item 2,1
 - Selecciona el item 1,3
 - Selecciona la fila 1

In [ ]:
import numpy as np

ventas = np.array([
    [554, 606, 710, 851],
    [1244, 898, 416, 1763],
    [841, 655, 1105, 1067]
])

item_2_1 = ventas[2, 1]

item_1_3 = ventas[1, 3]

fila_1 = ventas[1, :]

item_2_1, item_1_3, fila_1

In [ ]:
(655, 1763, array([1244,  898,  416, 1763]))

Solicita las filas con índices 0 y 1

In [ ]:
import numpy as np

ventas = np.array([
    [554, 606, 710, 851],
    [1244, 898, 416, 1763],
    [841, 655, 1105, 1067]
])

resultado = ventas[:2, :]

resultado
array([[ 554,  606,  710,  851],
       [1244,  898,  416, 1763]])

Ahora para solicitar las filas con indices 1 y 2

In [ ]:
import numpy as np

ventas = np.array([
    [554, 606, 710, 851],
    [1244, 898, 416, 1763],
    [841, 655, 1105, 1067]
])

resultado = ventas[1:3, :]

resultado
array([[1244,  898,  416, 1763],
       [ 841,  655, 1105, 1067]])

Quieres solo los elementos de la primera columna?

In [ ]:
import numpy as np

ventas = np.array([
    [554, 606, 710, 851],
    [1244, 898, 416, 1763],
    [841, 655, 1105, 1067]
])

resultado = ventas[:, 0]

resultado
array([ 554, 1244,  841])

Que la las columnas con indices 0 y 2?

In [ ]:
import numpy as np

ventas = np.array([
    [554, 606, 710, 851],
    [1244, 898, 416, 1763],
    [841, 655, 1105, 1067]
])

resultado = ventas[:, [0, 2]]

resultado
array([[ 554,  710],
       [1244,  416],
       [ 841, 1105]])

#### Por tu cuenta

Dado el siguiente arreglo

array([[1,2,3,4,5],
     [6,7,8,9,10],
     [11,12,13,14,15]])

- Selecciona la segunda fila
- Selecciona la primera y tercera fila
- Selecciona las tres columnas de enmedio

In [ ]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
])

fila_2 = arr[1, :]
fila_1_3 = arr[[0, 2], :]
columnas_medio = arr[:, 1:4]

fila_2, fila_1_3, columnas_medio

In [ ]:
(array([ 6,  7,  8,  9, 10]),
 array([[ 1,  2,  3,  4,  5],
        [11, 12, 13, 14, 15]]),
 array([[ 2,  3,  4],
        [ 7,  8,  9],
        [12, 13, 14]])
)

### 7.4.2.- Transponer

Con **reshape** puedes producir una copia superficial del arreglo con una nueva dimension. 

ventas = np.array([[ 500, 600, 550, 800],
 [1200, 800, 400,1000]])

Usa el arreglo anterior para darle dimension de 1x8

In [ ]:
import numpy as np

ventas = np.array([
    [500, 600, 550, 800],
    [1200, 800, 400, 1000]
])

resultado = ventas.reshape(1, 8)

resultado

In [ ]:
array([[ 500,  600,  550,  800, 1200,  800,  400, 1000]])

El metodo **resize** modifica la forma del original (no crea copia)

In [ ]:
import numpy as np

ventas = np.array([
    [500, 600, 550, 800],
    [1200, 800, 400, 1000]
])

ventas.resize(1, 8)

ventas

In [ ]:
array([[ 500,  600,  550,  800, 1200,  800,  400, 1000]])

Y **transpose** rapidamente le da la vuelta a filas y columnas, este se hace aplicando el atributo T, que no modifica el original, solo una vista.

In [ ]:
array([[ 500, 1200],
       [ 600,  800],
       [ 550,  400],
       [ 800, 1000]])

## 7.5.- Pandas - Series

Vamos a usar estos datos para Series - tiempo_web = pd.Series([160,256,98,108])

Este es el tiempo que invierten en videojuegos 4 estudiantes

In [ ]:
import pandas as pd

tiempo_web = pd.Series([160, 256, 98, 108])

print(tiempo_web)

In [ ]:
0    160
1    256
2     98
3    108
dtype: int64

Para crear una serie con el mismo elemento

In [ ]:
import pandas as pd

serie_repetida = pd.Series([5] * 4)

print(serie_repetida)
0    5
1    5
2    5
3    5
dtype: int64

Acceder a un elemento es facil

In [ ]:
import pandas as pd

tiempo_web = pd.Series([160, 256, 98, 108])

print(tiempo_web[1])
256

Series tiene acceso a los mismos metodos que arreglos para estadistica descriptiva

In [ ]:
import pandas as pd

tiempo_web = pd.Series([160, 256, 98, 108])

print(tiempo_web.mean())
print(tiempo_web.median())
print(tiempo_web.min())
print(tiempo_web.max())
print(tiempo_web.std())
155.5
134.0
98
256
69.6619772367584

Tambien, todo esto se puede resumir con **describe**

In [ ]:
import pandas as pd

tiempo_web = pd.Series([160, 256, 98, 108])

print(tiempo_web.describe())
count      4.000000
mean     155.500000
std       69.661977
min       98.000000
25%      106.500000
50%      134.000000
75%      183.000000
max      256.000000
dtype: float64

También podemos personalizar los indices de series a traves de index

['Laura','Daniel','Alberto','Eva'] 

Asigna esos nombres

In [ ]:
import pandas as pd

tiempo_web = pd.Series([160, 256, 98, 108], index=['Laura', 'Daniel', 'Alberto', 'Eva'])

print(tiempo_web)

In [ ]:
Laura      160
Daniel     256
Alberto     98
Eva        108
dtype: int64

O puedes usar un diccionario para eso:

In [ ]:
import pandas as pd

datos = {'Laura': 160, 'Daniel': 256, 'Alberto': 98, 'Eva': 108}
tiempo_web = pd.Series(datos)

print(tiempo_web)

In [ ]:
Laura      160
Daniel     256
Alberto     98
Eva        108
dtype: int64

Puedes llamar a los elementos personalizados

In [ ]:
import pandas as pd

datos = {'Laura': 160, 'Daniel': 256, 'Alberto': 98, 'Eva': 108}
tiempo_web = pd.Series(datos)

print(tiempo_web['Daniel'])
256

#### Por tu cuenta

Usa el generador aleatorio de NumPy (np.random.randint) para generar 6 calificaciones del 60 al 100 y guardarlos en una serie. 

A continuación arma las siguientes tareas:

- Convierte el arreglo en una serie llamada calificacion
- Determina la min, max y promedio
- Produce TODAS las estadisticas descriptivas

In [ ]:
import numpy as np
import pandas as pd

calificaciones = np.random.randint(60, 101, 6)
calificacion = pd.Series(calificaciones, name="Calificaciones")

min_cal = calificacion.min()
max_cal = calificacion.max()
promedio_cal = calificacion.mean()

estadisticas = calificacion.describe()

print(f"Calificaciones:\n{calificacion}\n")
print(f"Mínimo: {min_cal}")
print(f"Máximo: {max_cal}")
print(f"Promedio: {promedio_cal:.2f}\n")
print("Estadísticas descriptivas:")
print(estadisticas)

In [ ]:
Calificaciones:
0    93
1    77
2    84
3    63
4    86
5    91
Name: Calificaciones, dtype: int64

Mínimo: 63
Máximo: 93
Promedio: 82.33

Estadísticas descriptivas:
count     6.000000
mean     82.333333
std      11.675088
min      63.000000
25%      77.000000
50%      85.000000
75%      91.250000
max      93.000000
Name: Calificaciones, dtype: float64

## 7.6.- Pandas - DataFrames

##### Crear un Dataframe de un diccionario

Agarra este diccionario y conviertelo en un dataframe

 reg_peso = {'Vanesa':[68,67,66,65],'Kevin':[89,89,90,88],
 'Fernanda':[59,60,60,62],'Patricia':[70,68,67,65]}

In [ ]:
import pandas as pd

reg_peso = {
    'Vanesa': [68, 67, 66, 65],
    'Kevin': [89, 89, 90, 88],
    'Fernanda': [59, 60, 60, 62],
    'Patricia': [70, 68, 67, 65]
}

df = pd.DataFrame(reg_peso)
print(df)

In [ ]:
   Vanesa  Kevin  Fernanda  Patricia
0      68     89        59        70
1      67     89        60        68
2      66     90        60        67
3      65     88        62        65

##### El atributo Index

Añade los siguientes indices personalizados

peso.index = ['Mes 1','Mes 2','Mes 3','Mes 4']

In [ ]:
import pandas as pd

reg_peso = {
    'Vanesa': [68, 67, 66, 65],
    'Kevin': [89, 89, 90, 88],
    'Fernanda': [59, 60, 60, 62],
    'Patricia': [70, 68, 67, 65]
}

peso = pd.DataFrame(reg_peso)
peso.index = ['Mes 1', 'Mes 2', 'Mes 3', 'Mes 4']

print(peso)

In [ ]:
       Vanesa  Kevin  Fernanda  Patricia
Mes 1      68     89        59        70
Mes 2      67     89        60        68
Mes 3      66     90        60        67
Mes 4      65     88        62        65

##### Accesar Columnas

Selecciona la información de Fernanda

In [ ]:
print(peso['Fernanda'])
Mes 1    59
Mes 2    60
Mes 3    60
Mes 4    62
Name: Fernanda, dtype: int64

Selecciona la de Patricia pero como atributo

In [ ]:
print(peso.Patricia)
Mes 1    70
Mes 2    68
Mes 3    67
Mes 4    65
Name: Patricia, dtype: int64

##### Loc y iloc

Selecciona la información del Mes1 usando Loc

In [ ]:
print(peso.loc['Mes 1'])
Vanesa     68
Kevin      89
Fernanda   59
Patricia   70
Name: Mes 1, dtype: int64

Ahora solo la fila 1 usando iloc

In [ ]:
print(peso.iloc[1])
Vanesa     67
Kevin      89
Fernanda   60
Patricia   68
Name: Mes 2, dtype: int64

Ahora del Mes 1 al Mes 3 usando loc

In [ ]:
print(peso.loc['Mes 1':'Mes 3'])
       Vanesa  Kevin  Fernanda  Patricia
Mes 1      68     89        59        70
Mes 2      67     89        60        68
Mes 3      66     90        60        67

Saca filas especificas (mes 1 y 3) usando loc

In [ ]:
print(peso.loc[['Mes 1', 'Mes 3']])
       Vanesa  Kevin  Fernanda  Patricia
Mes 1      68     89        59        70
Mes 3      66     90        60        67

Y ahora los Meses 2 y 3 de Vanesa y Patricia solamente con loc

In [ ]:
print(peso.loc[['Mes 2', 'Mes 3'], ['Vanesa', 'Patricia']])
       Vanesa  Patricia
Mes 2      67        68
Mes 3      66        67

##### Indices Booleanos

Dime los pesos mayores a 70kg en la tabla

In [ ]:
print(peso[peso > 70])

In [ ]:
       Vanesa  Kevin  Fernanda  Patricia
Mes 1     NaN     89       NaN      70.0
Mes 2     NaN     89       NaN       NaN
Mes 3     NaN     90       NaN       NaN
Mes 4     NaN     88       NaN       NaN

Y ahora los pesos mayores a 65kg y menores a 80kg

In [ ]:
print(peso[(peso > 65) & (peso < 80)])

In [ ]:
       Vanesa  Kevin  Fernanda  Patricia
Mes 1     68.0     NaN       NaN       NaN
Mes 2     67.0     NaN       NaN      68.0
Mes 3     66.0     NaN       NaN      67.0
Mes 4     65.0     NaN       NaN      65.0

##### Accesar una celda especifica de un Dataframe

Que pasa si solo queremos cuanto pesaba Patricia en el mes 3? Usa at

In [ ]:
print(peso.at['Mes 3', 'Patricia'])
67

Resulta que Kevin en realidad pesaba 85kg en el mes 4, cambia su valor usando at

In [ ]:
peso.at['Mes 4', 'Kevin'] = 85
print(peso)

In [ ]:
       Vanesa  Kevin  Fernanda  Patricia
Mes 1      68     89        59        70
Mes 2      67     89        60        68
Mes 3      66     90        60        67
Mes 4      65     85        62        65

##### Estádistica descriptiva

Puedes usar el metodo **Describe** para sacar todas las estadisticas del dataframe

In [ ]:
print(peso.describe())
         Vanesa      Kevin   Fernanda   Patricia
count   4.000000   4.000000   4.000000   4.000000
mean   66.500000  88.250000  60.250000  67.500000
std     1.290994   2.217356   1.258306   2.081666
min    65.000000  85.000000  59.000000  65.000000
25%    65.750000  88.000000  60.000000  66.500000
50%    66.500000  89.000000  60.000000  67.000000
75%    67.250000  89.250000  60.250000  68.000000
max    68.000000  90.000000  62.000000  70.000000

También puedes cambiar la cantidad de decimales usando **Precision**

In [ ]:
pd.set_option('precision', 2)
print(peso.describe())

In [ ]:
         Vanesa  Kevin  Fernanda  Patricia
count      4.00   4.00      4.00      4.00
mean      66.50  88.25     60.25     67.50
std        1.29   2.22      1.26      2.08
min       65.00  85.00     59.00     65.00
25%       65.75  88.00     60.00     66.50
50%       66.50  89.00     60.00     67.00
75%       67.25  89.25     60.25     68.00
max       68.00  90.00     62.00     70.00

Y también se pueden aplicar los metodos de estadistica descriptiva individuales como mean

In [ ]:
print(peso.mean())
Vanesa      66.50
Kevin       88.25
Fernanda    60.25
Patricia    67.50
dtype: float64

##### Transponer

Si quisieramos voltear el dataframe, tendríamos que hacer el método T

In [ ]:
print(peso.T)
          Mes 1  Mes 2  Mes 3  Mes 4
Vanesa      68     67     66     65
Kevin       89     89     90     85
Fernanda    59     60     60     62
Patricia    70     68     67     65

Y ahora eso nos ayudaría a sacar los estadísticos para los meses en vez de para las personas

In [ ]:
print(peso.T.describe())
       Mes 1  Mes 2  Mes 3  Mes 4
count   4.00   4.00   4.00   4.00
mean    71.50  71.00  70.75  69.25
std     13.62  12.91  13.91  10.61
min     59.00  60.00  60.00  62.00
25%     65.25  67.25  66.75  65.00
50%     69.00  68.50  67.50  65.00
75%     75.25  89.00  90.00  85.00
max     89.00  89.00  90.00  85.00

Y el peso promedio por mes de nuestra gente

In [ ]:
print(peso.T.mean())
Mes 1    71.50
Mes 2    71.00
Mes 3    70.75
Mes 4    69.25
dtype: float64

##### Ordenar el Dataframe

Ahora vamos a arreglar el dataframe por fila, con los indices en orden descendente

In [ ]:
print(peso.sort_index(ascending=False))
       Vanesa  Kevin  Fernanda  Patricia
Mes 4      65     85        62        65
Mes 3      66     90        60        67
Mes 2      67     89        60        68
Mes 1      68     89        59        70

Las columnas en orden ascendente

In [ ]:
print(peso.sort_index(axis=1, ascending=True))
       Fernanda  Kevin  Patricia  Vanesa
Mes 1        59     89        70      68
Mes 2        60     89        68      67
Mes 3        60     90        67      66
Mes 4        62     85        65      65

Y también se vale ordenar los valores según una fila o columna especifica.  El siguiente código ordena de forma descendente los datos del DataFrame con respecto
a los valores del Mes 1.

In [ ]:
print(peso.sort_values(by='Mes 1', axis=1, ascending=False))

In [ ]:
       Kevin  Patricia  Vanesa  Fernanda
Mes 1     89        70      68        59
Mes 2     89        68      67        60
Mes 3     90        67      66        60
Mes 4     85        65      65        62